# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Angular Build CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'README.md'
      - '.gitignore'
      - 'docs/**'
      - 'images/**'
      - 'k8s/**'
      - 'docker-compose.yml'
      - 'docker/**'
      - '.gitattributes'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 20.19, 22.22, 24.13 ]
    name: Angular Build Node-${{ matrix.node }}
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v6

      - name: Setup Node Js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Print Node Npm Versions
        run: |
          node -v
          npm -v

      - name: Install npm dependencies
        run: |
          npm ci

      - name: Print All Versions
        run: |
          npx ng version

      - name: Build Angular Application
        run: |
          npm run build

#      - name: Test
#        run: npm run test
